# The sequence of triangle numbers is generated by adding the natural numbers.
# What is the value of the first triangle number to have over five hundred divisors?

import math

def triangle(n):
    tri = 0
    for i in range(n):
        tri += i
    return tri

def factors(n):
    factN = 0
    root = math.sqrt(n)
    for i in range(1, math.ceil(root)):
        if n % i == 0:
            factN += 2
    if root.is_integer():
        factN += 1
    return factN

run = True
n = 1
while run:
    tri = triangle(n)
    if factors(tri) > 500:
        run = False
        print(n, tri)
    n += 1

# Solves it in a bit under 10 seconds