# Project Euler Problem 29
# How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

# It's literally this simple, and runs for approx. 0.06s without any optimizations or mathematical analysis
# <3 modern tech and computational power

them = set()

for a in range(2, 101):
    for b in range(2, 101):
        them.add(a**b)

print(len(them))